# Generated by Django 6.0.4 on 2026-04-08 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('missed_punch', 'Missed Punch'), ('timesheet_submitted', 'Timesheet Submitted'), ('timesheet_approved', 'Timesheet Approved'), ('timesheet_rejected', 'Timesheet Rejected'), ('pto_approved', 'PTO Approved'), ('pto_rejected', 'PTO Rejected'), ('pto_request', 'PTO Request'), ('overtime_alert', 'Overtime Alert'), ('shift_reminder', 'Shift Reminder'), ('system', 'System')], max_length=30)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('push', 'Push')], default='in_app', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
