# Generated by Django 6.0.4 on 2026-04-08 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTOPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal')], max_length=20)),
                ('accrual_rate_hours', models.DecimalField(decimal_places=2, help_text='Hours accrued per period', max_digits=5)),
                ('accrual_period', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='biweekly', max_length=20)),
                ('max_balance_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_carry_over_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('waiting_period_days', models.PositiveIntegerField(default=0, help_text='Days before accrual starts')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'PTO Policies',
            },
        ),
        migrations.CreateModel(
            name='PTORequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal'), ('bereavement', 'Bereavement'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_requests', to='core.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pto_requests', to='core.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PTOAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal')], max_length=20)),
                ('balance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('accrued_this_period', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('used_this_period', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carry_over_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('as_of_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_accruals', to='core.employee')),
            ],
            options={
                'ordering': ['-as_of_date'],
                'unique_together': {('employee', 'leave_type', 'as_of_date')},
            },
        ),
    ]
