# Generated by Django 6.0.4 on 2026-04-08 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('break_start', 'Break Start'), ('break_end', 'Break End'), ('edit', 'Edit'), ('approve', 'Approve'), ('reject', 'Reject'), ('delete', 'Delete')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to='core.employee')),
                ('target_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to='core.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_in_method', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('pin', 'PIN Kiosk'), ('qr', 'QR Code'), ('manager', 'Manager Entry'), ('api', 'API')], default='web', max_length=20)),
                ('clock_out_method', models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('pin', 'PIN Kiosk'), ('qr', 'QR Code'), ('manager', 'Manager Entry'), ('api', 'API')], max_length=20, null=True)),
                ('clock_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_within_geofence', models.BooleanField(blank=True, null=True)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_break_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('missed_out', 'Missed Clock-Out'), ('edited', 'Edited'), ('pending_review', 'Pending Review')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edit_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_entries', to='core.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.employee')),
            ],
            options={
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-clock_in'],
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_type', models.CharField(choices=[('meal', 'Meal Break'), ('rest', 'Rest Break'), ('personal', 'Personal'), ('other', 'Other')], default='rest', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.timeentry')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
