# Generated by Django 6.0.4 on 2026-04-08 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_shift_hours_for_break', models.DecimalField(decimal_places=1, default=4.0, max_digits=4)),
                ('break_duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_paid', models.BooleanField(default=False)),
                ('max_breaks_per_shift', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='break_policies', to='core.department')),
            ],
            options={
                'verbose_name_plural': 'Break Policies',
            },
        ),
        migrations.CreateModel(
            name='OvertimeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('daily_threshold_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('weekly_threshold_hours', models.DecimalField(decimal_places=1, default=40.0, max_digits=4)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('double_time_threshold_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('double_time_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank to apply globally', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_rules', to='core.department')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
